name: virtualfleet-recovery
channels:
  - conda-forge
dependencies:
  - python=3.9
  - xarray
  - parcels>=3.0.0
  - dask
  - distributed
  - dask-kubernetes
  - bottleneck
  - gcsfs
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
#  - nbserverproxy
  - jupyter
  - jupyterlab>=0.35
  - jupyterlab_launcher
  - jupyter_client
  - jupyter_server
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - graphviz
  - nodejs
  - watermark
  - scikit-learn
  - shapely
  - cartopy>=0.19.0
  - seaborn
  - xhistogram
  - argopy>=0.1.14
  - tqdm
  - py
  - pydap
  - pip
  - pip:
    - jupyter-server-proxy
    - netCDF4
    - erddapy
    - gitpython
#    - motuclient
    - cmocean
    - progressbar
    - cgen
    - pymbolic
    - memory-profiler
    - line-profiler
    - Flask
    - flask-swagger
    - geojson
    - dominate
    - copernicusmarine>=1.0<=2.0
    - git+https://github.com/euroargodev/VirtualFleet.git@master


