name: vfreco-prod
channels:
  - conda-forge
dependencies:
  - python=3.9

# CORE:
  - aiohttp = 3.8.4
  - erddapy = 2.0.1
  - fsspec = 2023.5.0
  - netCDF4 = 1.6.3
  - packaging = 23.1
  - requests = 2.31.0
  - scipy = 1.10.1
  - toolz = 0.12.0
  - xarray = 2023.5.0
  - parcels = 2.4.1
  - pydap = 3.4.0
  - dominate = 2.8.0
#  - flask = 2.3.2
  - scikit-learn = 1.2.2
  - geojson = 3.0.1

# EXT.UTIL:
  - gsw = 3.6.16
  - tqdm = 4.65.0
  - zarr = 2.14.2

# EXT.PERF:
  - dask = 2023.5.1
  - distributed = 2023.5.1
  - pyarrow = 12.0.0

# EXT.PLOT:
  - IPython = 8.13.2
  - cartopy = 0.21.1
  - ipykernel = 6.23.1
  - ipywidgets = 8.0.6
  - matplotlib = 3.7.1
  - seaborn = 0.12.2

# DEV:
  - black = 23.3.0
  - bottleneck = 1.3.7
  - cfgrib = 0.9.10.3
  - cftime = 1.6.2
#  - conda = -
  - flake8 = 6.0.0
#  - nc-time-axis = -
  - numpy = 1.24.3
  - pandas = 2.0.2
  - pip = 23.1.2
  - pytest = 7.3.1
  - pytest-cov = 4.1.0
  - pytest-env = 0.8.1
  - pytest-localftpserver = 1.1.4
  - pytest-reportlog
  - aiofiles
  - setuptools = 67.7.2
#  - sphinx = -

  - pip
  - pip:
    - git+https://github.com/euroargodev/argopy.git@master  # *
    - Flask
    - flask-swagger
